# Generated by Django 4.2.5 on 2023-11-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0002_alter_note_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
